### ISSUE TITLE
Provide a torrent file/link

### ISSUE THREAD

**Issue by kelson42** [kiwix/python_storagelib#2]
We can not rely only on HTTP to download big files from a S3 cache. The library should provide a way to furnish a `.torrent` pointing the the web seed HTTP link.

Seems necessary (at least) for:
* https://github.com/openzim/zimfarm/issues/483
* https://github.com/kiwix/cardshop/issues/116

**Comment by kelson42** [comment]
@rgaudin Any comment on this ticket? Is that the right place?

**Comment by rgaudin** [comment]
No, I think not. What I understand is that it's meant to ease the upload of both a file and a torrent for it. That would be in kiwixstorage. At the moment, cardshop issue was implemented without adding that to kiwixstorage because it's simple and also because kiwixstorage has grown to be a very large class that should be refactored.
